Fixed compatibility with NumPy 2.2.0
Discovered an error in function multivariate_gaussian(x, mu, cov). This fix makes it compatible with the latest NumPy version.

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.